### ISSUE TITLE
Author's Issue: Please delete this repository.

### ISSUE THREAD

**Issue by Stereoarts** [ZombieMaze/Final#1]
Author's Issue: Please delete this repository.
I don't accept upload codes, images, models, motions, and documents for public space. Please delete this repository.

And you must check model / motion's license. You **must** read readme. This model is usable within MMD. And denied redistribution.
Please don't use it without author's permission. (Please use for private only.)

**Comment by fffonion** [comment]
Thie model author permitted unattended distributing and editing of the model as long as the credit file as shipped together, which is included in this repo.
Or you are talking about mmd4mecanim?

**Comment by Stereoarts** [comment]
Please each & original model's readme.txt.

This model is **not** permitted redistribution without processing.
And **not** permitted using except MMD.(This model is usable for MMD only.)

And please see also,
http://piapro.jp/license/pcl
- Denied using for public order and morality. (it measn violence & sexual.)
You **must** think, they are the "singer".

**Comment by Stereoarts** [comment]
And, please, please don't upload any third author's contents.
I'm blamed from them & I may / should discontinue develop for MMD4Mecanim if it happens some problems.

Therefore, I must check github & notice some developers everyday. I consume many private & develop times.I'm very tired.

**Comment by fffonion** [comment]
Acknowledged, will delete this repo soon.
Thanks for your contribution to MMD4Mecanim.
